site_name: Xuc's Docs
site_author: Xuc Pan
copyright: Copyright &copy; 2023 Xuc Pan
repo_url: https://github.com/Panxuc/docs
repo_name: Panxuc/docs
edit_uri: edit/main/docs/
theme:
  name: material
  logo: assets/icon.png
  favicon: assets/images/favicon.png
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides/.overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.footer
    # - navigation.indexes
    - navigation.instant
    # - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.follow
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to Dark Mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to Light Mode
extra:
  alternate:
    - name: English
      link: ./en/
      lang: en
    - name: 中文（简体）
      link: ./zh/
      lang: zh
    - name: 中文（繁體）
      link: ./zh-TW/
      lang: zh-TW
    - name: 日本語
      link: ./ja/
      lang: ja
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/panxuc/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/XucPan
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/panxuc/
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/33071481
    - icon: fontawesome/brands/github
      link: https://panxuc.github.io/
    - icon: fontawesome/brands/steam
      link: https://steamcommunity.com/id/panxuc/
nav:
  - Home: index.zh.md
  - Projects:
      - projects/index.zh.md
      - Coursework:
          - projects/cpd1.zh.md
          - projects/cpd2.zh.md
      - Beyond Course:
          - projects/eesastsd.zh.md
          - projects/eesasthd.zh.md
  - Notes:
      - notes/index.zh.md
      - Life in Tsinghua:
          - notes/socialmedia.zh.md
          - notes/utilities.zh.md
          - notes/network.zh.md
          - notes/courses.zh.md
      - OS & Software:
          - notes/windows11.zh.md
          - notes/archlinux.zh.md
      - Games:
          - notes/games.zh.md
          - Galgames:
              - notes/galgames/yuzusoft.zh.md
  - About:
      - about/index.zh.md
      - about/about.zh.md
      - about/about-site.zh.md
      - about/license.md
plugins:
  - search:
      lang:
        - en
        - zh
        - zh-TW
        - ja
  - i18n:
      default_language: zh
      languages:
        en: english
        zh: 中文（简体）
        zh-TW: 中文（繁體）
        ja: 日本語
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: Panxuc
      repo: docs
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
