site_name: Xuc's Docs
site_url: https://docs.panxuc.com/
site_author: Xuc Pan
site_description: Xuc's Docs
repo_name: Panxuc/docs
repo_url: https://github.com/Panxuc/docs
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2023 Xuc Pan
theme:
  name: material
  logo: assets/icon.png
  favicon: assets/images/favicon.png
  icon:
    repo: fontawesome/brands/github
  language: zh
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: 浅色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: 深色模式
extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/panxuc/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/XucPan
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/panxuc/
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/33071481
    - icon: fontawesome/brands/github
      link: https://panxuc.github.io/
    - icon: fontawesome/brands/steam
      link: https://steamcommunity.com/id/panxuc/
plugins:
  - search:
      lang:
        - zh
      jieba_dict: dict.txt
  - mkdocs-video
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys:
      separator: +
      strict: false
      camel_case: false
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: Panxuc
      repo: docs
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - 主页: index.md
  - 作业:
      - coursework/index.md
      - coursework/cpd1.md
      - coursework/cpd2.md
      - coursework/pdmes.md
      - 数据与算法:
          - coursework/daa/README.md
          - A + B Problem:
              - 题目: coursework/daa/prob/1001.md
              - 答案: coursework/daa/ans/1001.md
          - The Nth Number in Fibonacci Sequence:
              - 题目: coursework/daa/prob/1002.md
              - 答案: coursework/daa/ans/1002.md
          - 丢失的练习册:
              - 题目: coursework/daa/prob/2023201.md
              - 答案: coursework/daa/ans/2023201.md
          - 军训排队:
              - 题目: coursework/daa/prob/2023202.md
              - 答案: coursework/daa/ans/2023202.md
          - 比武:
              - 题目: coursework/daa/prob/2023203.md
              - 答案: coursework/daa/ans/2023203.md
          - 缺损二叉树:
              - 题目: coursework/daa/prob/2023204.md
              - 答案: coursework/daa/ans/2023204.md
          - 信息传递:
              - 题目: coursework/daa/prob/2023205.md
              - 答案: coursework/daa/ans/2023205.md
          - 跳跳乐:
              - 题目: coursework/daa/prob/2023206.md
              - 答案: coursework/daa/ans/2023206.md
          - 带限矩阵方程组求解:
              - 题目: coursework/daa/prob/2023207.md
              - 答案: coursework/daa/ans/2023207.md
          - 缺失数据恢复:
              - 题目: coursework/daa/prob/2023208.md
              - 答案: coursework/daa/ans/2023208.md
          - 小明的火车旅行计划:
              - 题目: coursework/daa/prob/2023209.md
              - 答案: coursework/daa/ans/2023209.md
  - 项目:
      - projects/index.md
      - projects/eesastsd.md
      - projects/eesasthd.md
  - 清华:
      - tsinghua/index.md
      - tsinghua/socialmedia.md
      - tsinghua/utilities.md
      - tsinghua/network.md
      - tsinghua/courses.md
      - tsinghua/locations.md
  - 系统:
      - os/index.md
      - os/windows11.md
      - os/archlinux.md
      - os/steamos.md
      - os/android.md
  - 语言:
      - languages/index.md
      - languages/html.md
      - languages/markdown.md
      - languages/typst.md
      - languages/latex.md
      - Python:
          - languages/python/matplotlib.md
  - 软件:
      - softwares/index.md
      - softwares/vim.md
      - softwares/platformio.md
  - 游戏:
      - games/index.md
      - games/mahjong.md
      - games/aceattorney.md
      - games/persona.md
      - Galgames:
          - games/galgames/yuzusoft.md
  - 关于:
      - about/index.md
      - about/license.md
