site_name: Xuc's Docs
site_author: Xuc Pan
copyright: Copyright &copy; 2023 Xuc Pan
repo_url: https://github.com/Panxuc/docs
repo_name: Panxuc/docs
edit_uri: edit/main/docs/
theme:
  name: material
  logo: assets/icon.png
  favicon: assets/images/favicon.png
  icon:
    repo: fontawesome/brands/github
  language: zh
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    # - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to Dark Mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to Light Mode
extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/panxuc/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/XucPan
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/panxuc/
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/33071481
    - icon: fontawesome/brands/github
      link: https://panxuc.github.io/
    - icon: fontawesome/brands/steam
      link: https://steamcommunity.com/id/panxuc/
nav:
  - 主页: index.md
  - 项目:
      - projects/index.md
      - 课程之内:
          - projects/coursework/index.md
          - projects/coursework/cpd1.md
          - projects/coursework/cpd2.md
      - 课程之外:
          - projects/beyondcourse/index.md
          - projects/beyondcourse/eesastsd.md
          - projects/beyondcourse/eesasthd.md
  - 笔记:
      - notes/index.md
      - 清华生活:
          - notes/tsinghua/index.md
          - notes/tsinghua/socialmedia.md
          - notes/tsinghua/utilities.md
          - notes/tsinghua/network.md
          - notes/tsinghua/courses.md
          - notes/tsinghua/locations.md
      - 操作系统与软件:
          - notes/os/index.md
          - notes/os/windows11.md
          - notes/os/archlinux.md
          - notes/os/steamos.md
          - notes/os/android.md
      - 游戏与娱乐:
          - notes/games/index.md
          - notes/games/aceattorney.md
          - notes/games/touhou.md
          - Galgames:
              - notes/games/galgames/index.md
              - notes/games/galgames/yuzusoft.md
  - 关于:
      - about/index.md
      - about/license.md
plugins:
  - search:
      lang:
        - zh
      jieba_dict: dict.txt
  - mkdocs-video
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys:
      separator: +
      strict: false
      camel_case: false
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: Panxuc
      repo: docs
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
